input:
  generate:
    interval: '@every 5s'
    mapping: 'root = 1'

pipeline:
  processors:
    - sql_select:
        driver: postgres
        dsn: postgres://postgres:123@localhost:5432/accountdb?sslmode=disable
        table: event
        columns: [ id, entity_id, event_type ]
        where: status = 'C'
        suffix: 'order by created_at asc'
    - unarchive:
        format: json_array
    - mapping: |
        root.id = json("id")
        root.entity_id = json("entity_id")
        meta topic = json("event_type")
output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - kafka:
          addresses: [ "localhost:9092" ]
          topic: '${!meta("topic")}'
          client_id: "polling-cdc"

      - sql_raw:
          driver: postgres
          dsn: postgres://postgres:123@localhost:5432/accountdb?sslmode=disable
          args_mapping: root = [this.id]
          query: |
            UPDATE event
              SET status = 'S'
            WHERE id = $1
