linters:
  enable:
    - bodyclose
    - gocognit
    - dogsled
    - dupword
    - errchkjson
    - gocyclo
    - loggercheck
    - ineffassign
    - wsl
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - errcheck


