api:
  bind: ${API_BIND:localhost}
  port: ${API_PORT:8080}

db:
  url: postgres://localhost:5432/accountdb
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:123}

migration:
  name: postgres
  dir: /migration

bus: 
  broker: localhost:9092
  groupId: ${BUS_GROUP_ID:account}

mongo:
  url: mongodb://root:123@localhost:27017/auditdb?authSource=admin&authMechanism=SCRAM-SHA-1
  database: auditdb
