services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: accountdb
    ports:
      - 5432:5432
    volumes:
      - ./compose/pg/data:/var/lib/postgresql/data

